
CREATE PROCEDURE ActivarVariante
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        UPDATE VariantesPerfume SET Activo=1 WHERE Id=@Id;
        SELECT @Id;
    COMMIT TRANSACTION
END