CREATE PROCEDURE ActivarMarca
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        UPDATE Marcas SET Activo=1 WHERE Id=@Id;
        SELECT @Id;
    COMMIT TRANSACTION
END