
CREATE PROCEDURE ActivarBodySpray
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        UPDATE BodySprays SET Activo=1 WHERE Id=@Id;
        SELECT @Id;
    COMMIT TRANSACTION
END