
CREATE PROCEDURE ActivarNota
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        UPDATE Notas SET Activo=1 WHERE Id=@Id;
        SELECT @Id;
    COMMIT TRANSACTION
END