
CREATE PROCEDURE ActivarPerfume
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        UPDATE Perfumes SET Activo=1 WHERE Id=@Id;
        SELECT @Id;
    COMMIT TRANSACTION
END