
CREATE PROCEDURE EliminarBodySpray
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        UPDATE BodySprays SET Activo=0 WHERE Id=@Id;
        SELECT @Id;
    COMMIT TRANSACTION
END