
CREATE PROCEDURE EliminarPerfume
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        UPDATE Perfumes SET Activo=0 WHERE Id=@Id;
        SELECT @Id;
    COMMIT TRANSACTION
END