
CREATE PROCEDURE EliminarBody
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        UPDATE Bodys SET Activo=0 WHERE Id=@Id;
        SELECT @Id;
    COMMIT TRANSACTION
END