CREATE PROCEDURE EliminarNota
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        UPDATE Notas SET Activo=0 WHERE Id=@Id;
        SELECT @Id;
    COMMIT TRANSACTION
END