
CREATE PROCEDURE EliminarNotaDePerfume
    @IdPerfume UNIQUEIDENTIFIER, @IdNota UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        DELETE FROM NotasPerfume WHERE IdPerfume=@IdPerfume AND IdNota=@IdNota;
        SELECT @IdNota;
    COMMIT TRANSACTION
END